apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: caporderack
    purpose: capture-orders
  name: caporderack
spec:
  replicas: 5
  selector:
    matchLabels:
      app: caporderack
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: caporderack
    spec:
      containers:
      - env:
        - name: TEAMNAME
          value: RoboClusters
        - name: MONGOURL
          value: mongodb://robo-dev-mongodb:27017
        - name: EVENTURL
          value: "https://robo-dev-event-hub.servicebus.windows.net/robo-dev-event-hub"
        - name: EVENTPOLICYNAME
          value: "RootManageSharedAccessKey"
        - name: EVENTPOLICYKEY
          value: "Ea6RMUMhTXF00gF5cmasQUzYTlVNu//zK8F9dSIt8Hw="
        - name: PARTITIONKEY
          value: "1"
        image: sabbour/captureorderack-netcore
        name: caporderack
        resources: {}
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: caporderack-svc
spec:
  selector:
    app: caporderack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
